# Defaults tasks for role ucarp

- name: Importing specific distro variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - vars

- name: Installing required packages for ucarp HA
  yum:
    name: "{{ ucarp_pkgs }}"
    state: installed

- name: Defining common conf
  template:
    src: vip-common.conf.j2
    dest: /etc/ucarp/vip-common.conf

- name: Defining VIP addresses through list
  template:
    src: vip.conf.j2
    dest: "/etc/ucarp/vip-{{ item.vid }}.conf"
    mode: '0600'
  with_items: "{{ ucarp_vip_list }}"
  loop_control:
    label: "{{ item.vip_address }}"
  register: carp_config
  tags:
    - config

- name: Defining VIP carp pass
  template:
    src: vip.pwd.j2
    dest: "/etc/ucarp/vip-{{ item.vid }}.pwd"
    mode: '0600'
  with_items: "{{ ucarp_vip_list }}"
  loop_control:
    label: "{{ item.vip_address }}"
  tags:
    - config

- name: Ensuring VIP are reloaded on changes
  service:
    name: "ucarp@{{ item.item.vid }}"
    state: restarted
    enabled: True
  with_items: "{{ carp_config.results }}"
  when: item is changed
  tags:
    - config
  loop_control:
    label: "{{ item.item.vip_address }}"
